
export const ordersData = [
    {
    id: 1,
    customer: 'Maria Santos',
    orderNumber: '#ORD-2024-001',
    status: 'Pending',
    items: 'Pizza Margherita x2, Coke x1',
    total: '₱650.00',
    date: '2025-08-02',
  },
  {
    id: 2,
    customer: 'John Dela Cruz',
    orderNumber: '#ORD-2024-002',
    status: 'Preparing',
    items: 'Burger Combo x1, Fries x2',
    total: '₱450.00',
    date: '2025-08-02',
  },
  {
    id: 3,
    customer: 'Anna Reyes',
    orderNumber: '#ORD-2024-003',
    status: 'Delivered',
    items: 'Chicken Wings x1, Rice x2',
    total: '₱380.00',
    date: '2025-08-01',
  },
  {
    id: 4,
    customer: 'Robert Garcia',
    orderNumber: '#ORD-2024-004',
    status: 'Cancelled',
    items: 'Pasta Carbonara x1, Garlic Bread x1',
    total: '₱520.00',
    date: '2025-08-01',
  },
  {
    id: 5,
    customer: 'Sofia Mendoza',
    orderNumber: '#ORD-2024-005',
    status: 'Delivered',
    items: 'Lechon Kawali x1, Steamed Rice x2',
    total: '₱720.00',
    date: '2025-08-02',
  },
  {
    id: 6,
    customer: 'Miguel Torres',
    orderNumber: '#ORD-2024-006',
    status: 'Preparing',
    items: 'Adobo Chicken x1, Pancit x1, Lumpia x5',
    total: '₱580.00',
    date: '2025-08-03',
  },
  {
    id: 7,
    customer: 'Carmen Lopez',
    orderNumber: '#ORD-2024-007',
    status: 'Pending',
    items: 'Sinigang na Baboy x1, Rice x3',
    total: '₱450.00',
    date: '2025-08-03',
  },
  {
    id: 8,
    customer: 'Luis Fernandez',
    orderNumber: '#ORD-2024-008',
    status: 'Delivered',
    items: 'Grilled Bangus x1, Garlic Rice x2',
    total: '₱390.00',
    date: '2025-08-02',
  },
  {
    id: 9,
    customer: 'Isabella Cruz',
    orderNumber: '#ORD-2024-009',
    status: 'Preparing',
    items: 'Bicol Express x1, Rice x2, Halo-halo x1',
    total: '₱520.00',
    date: '2025-08-03',
  },
  {
    id: 10,
    customer: 'Carlos Villanueva',
    orderNumber: '#ORD-2024-010',
    status: 'Cancelled',
    items: 'Kare-kare x1, Bagoong x1, Rice x2',
    total: '₱680.00',
    date: '2025-08-01',
  },
  {
    id: 11,
    customer: 'Rosario Bautista',
    orderNumber: '#ORD-2024-011',
    status: 'Delivered',
    items: 'Crispy Pata x1, Rice x3, San Miguel x2',
    total: '₱890.00',
    date: '2025-08-02',
  },
  {
    id: 12,
    customer: 'Eduardo Ramos',
    orderNumber: '#ORD-2024-012',
    status: 'Pending',
    items: 'Sisig x1, Rice x1, Red Horse x1',
    total: '₱320.00',
    date: '2025-08-03',
  },
];


export const customers = [
  {
    id: 1,
    name: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '09171234567',
    orders: 3,
    lastOrder: '2025-08-02',
    totalSpent: '₱2,100.00',
    items: 'Anime Shirt, Hoodie, Cap',
  },
  {
    id: 2,
    name: 'John Dela Cruz',
    email: 'john.delacruz@email.com',
    phone: '09181234567',
    orders: 2,
    lastOrder: '2025-08-01',
    totalSpent: '₱1,200.00',
    items: 'Anime Shirt, Keychain',
  },
  {
    id: 3,
    name: 'Anna Reyes',
    email: 'anna.reyes@email.com',
    phone: '09191234567',
    orders: 1,
    lastOrder: '2025-07-30',
    totalSpent: '₱650.00',
    items: 'Anime Hoodie',
  },
  {
    id: 4,
    name: 'Robert Garcia',
    email: 'robert.garcia@email.com',
    phone: '09201234567',
    orders: 4,
    lastOrder: '2025-08-02',
    totalSpent: '₱2,800.00',
    items: 'Anime Shirt, Cap, Hoodie, Socks',
  },
  {
    id: 5,
    name: 'Sarah Kim',
    email: 'sarah.kim@email.com',
    phone: '09211234567',
    orders: 2,
    lastOrder: '2025-07-31',
    totalSpent: '₱1,450.00',
    items: 'Anime Poster, Stickers',
  },
  {
    id: 6,
    name: 'Michael Torres',
    email: 'michael.torres@email.com',
    phone: '09221234567',
    orders: 5,
    lastOrder: '2025-08-03',
    totalSpent: '₱3,200.00',
    items: 'Anime Shirt, Hoodie, Cap, Poster, Keychain',
  },
  {
    id: 7,
    name: 'Jenny Lim',
    email: 'jenny.lim@email.com',
    phone: '09231234567',
    orders: 1,
    lastOrder: '2025-07-29',
    totalSpent: '₱890.00',
    items: 'Anime Figurine',
  },
  {
    id: 8,
    name: 'Carlos Mendoza',
    email: 'carlos.mendoza@email.com',
    phone: '09241234567',
    orders: 3,
    lastOrder: '2025-08-01',
    totalSpent: '₱2,350.00',
    items: 'Anime Hoodie, Poster, Bag',
  },
  {
    id: 9,
    name: 'Lisa Chan',
    email: 'lisa.chan@email.com',
    phone: '09251234567',
    orders: 2,
    lastOrder: '2025-07-28',
    totalSpent: '₱1,100.00',
    items: 'Anime Shirt, Socks',
  },
  {
    id: 10,
    name: 'David Rodriguez',
    email: 'david.rodriguez@email.com',
    phone: '09261234567',
    orders: 4,
    lastOrder: '2025-08-02',
    totalSpent: '₱2,750.00',
    items: 'Anime Hoodie, Cap, Keychain, Stickers',
  },
  {
    id: 11,
    name: 'Grace Tan',
    email: 'grace.tan@email.com',
    phone: '09271234567',
    orders: 1,
    lastOrder: '2025-07-27',
    totalSpent: '₱520.00',
    items: 'Anime Poster',
  },
  {
    id: 12,
    name: 'Antonio Cruz',
    email: 'antonio.cruz@email.com',
    phone: '09281234567',
    orders: 6,
    lastOrder: '2025-08-03',
    totalSpent: '₱4,100.00',
    items: 'Anime Shirt, Hoodie, Cap, Poster, Figurine, Bag',
  },
];


export const summaryData = {
  highlights: [
    {
      title: 'Anime Shirts',
      description: 'Popular anime shirts available in various designs and sizes.',
      count: 12,
      unit: 'styles',
    },
    {
      title: 'Hoodies',
      description: 'Cozy anime hoodies for all seasons.',
      count: 7,
      unit: 'styles',
    },
    {
      title: 'Caps',
      description: 'Anime-themed caps for fans.',
      count: 5,
      unit: 'styles',
    },
    {
      title: 'Keychains',
      description: 'Collectible anime keychains.',
      count: 20,
      unit: 'designs',
    },
    {
      title: 'Socks',
      description: 'Fun anime socks for everyday wear.',
      count: 8,
      unit: 'styles',
    },
  ],
  featured: [
    {
      name: 'Best Seller',
      product: 'Naruto Anime Shirt',
      sold: 30,
      revenue: '₱4,500.00',
    },
    {
      name: 'New Arrival',
      product: 'Attack on Titan Hoodie',
      sold: 10,
      revenue: '₱2,000.00',
    },
  ],
  customerFeedback: [
    {
      customer: 'Maria Santos',
      feedback: 'Great quality shirts and fast delivery!'
    },
    {
      customer: 'John Dela Cruz',
      feedback: 'Love the hoodie! Will order again.'
    },
    {
      customer: 'Anna Reyes',
      feedback: 'Keychains are super cute.'
    },
  ],
};
